### ISSUE TITLE
Windows app locks up when opening Python console

### ISSUE THREAD

**Issue by NathanDunfield** [regina-normal/regina#71]
With Regina 6.0.1 (64 bit) on Windows 10 Pro (version 21H1) on a Surface Pro 5 (i5-7330 U), the following locks up the GUI:

a) Start Regina.
b) Click on terminal icon.

The Python console window is created and contains a single line of text "Regina 6.0.1".  After a minute, the window's title bar is labeled "Not Responding".   One must then force quit the application.

The problem is intermittent, occurring roughly 1 in 4 times I try the above steps.  

I then tested Regina 6.0.1 on three other systems: two Windows 10 Enterprise with 20H2 and one with macOS 10.15.  I saw the same intermittent issue on all three, but the on macOS it manifested it self much more rarely, in fact I only saw it once.

**Comment by WPettersson** [comment]
I've managed to see a crash on Linux (Gentoo) on 6.0.1 when trying to use the Python console too, but not sure if it's the same thing. Am debugging now.

**Comment by NathanDunfield** [comment]
@unhyperbolic Matthias do you have any suggestions?

**Comment by baburton** [comment]
Sorry on a phone and been dealing with olympiad dramas all week. (Hello again from
IOI 2021.)

But: my guess without ANY testing or looking or information would be that the crash relates to the fact that the GUI uses multiple subinterpreters. I had some dramas with the GIL on different platforms in the barely-released 5.95 under some older python3 versions that I found and fixed in 5.96.

- b.

--

Prof. Benjamin Burton
Computational Geometry & Topology Group
School of Mathematics and Physics
The University of Queensland, Australia

UQ ALLY   ::   Supporting and celebrating the diversity of sexuality, gender and sex at UQ.   Pronouns: He, him, his

On 26 Jun 2021, at 10:32 pm, Nathan Dunfield ***@***.***> wrote:

﻿

@unhyperbolic<https://github.com/unhyperbolic> Matthias do you have any suggestions?

**Comment by baburton** [comment]
Hmm. Out of interest, is anyone able to reproduce this with git master?

Not only has there been some major, major overhaul with regina 7.0, but also since 7.1 regina will only support python3 (not python2). I do remember that python2 and python3 had different gotchas with the GIL, and so it's not inconceivable that what you saw was exclusively a python2 problem and therefore no longer exists.

(I've not seen this problem at all this year, and I'm using the GUI on macOS a fair bit, and I have some students who use the GUI with python on Windows a lot.)

**Comment by WPettersson** [comment]
Just tried latest master, and could not replicate.

**Comment by NathanDunfield** [comment]
Tried out with the 7.1 binary release on Windows 10 (21H2) on the same Surface Pro 5 (i5-7330 U) as in the original report.  Unfortunately, the problem is still there, though it occurs much less frequently, say 1 time in 10 rather than 1 in 4.


![Untitled](https://user-images.githubusercontent.com/3139290/193065973-8be1f1a2-b7fb-42c0-89f1-6dda6c0979d0.png)

**Comment by baburton** [comment]
Aieee ok, thanks - reopening.

If anyone else is looking at this: the pybind11::gil_scoped_acquire class is broken with subinterpreters, since it confuses the python thread state (which should be unique for each subinterpreter/thread combination) with the actual native OS threads. In 7.1 I tried to fix this by commenting out instances that looked unnecessary in regina's setting, and by replacing gil_scoped_acquire with a more robust safe_gil_scoped_acquire for instances that were still necessary. But perhaps this isn't where it's locking up.

I wonder if the issue with the surface is that it has fewer cores, and therefore threads are more likely to be serialised in a chunky way that means "rare" race conditions are less rare. I saw some of this happening in windows VMs when running the test suite (one thread would get a very long way before another would make any progress at all).

**Comment by baburton** [comment]
Also btw if anyone does manage to reproduce this on a machine where it's convenient/possible to do this: I'd be super happy if you're able to somehow attach a debugger to the process and thereby get a stack trace showing exactly where it's locked up and in which threads. (I'm still struggling to reproduce it.)

**Comment by baburton** [comment]
FYI I'm trying very hard to reproduce this on my windows 10 VM and still cannot.

I note that it's locking up in the *middle* of the command: print(welcome()). Here welcome() returns a multi-line string, and it's locking up around the first newline (which might be the first point at which the output stream tries to flush its output to the console). I note that pybind11 *does* have a gil_scoped_acquire buried inside the pybind11::detail::pythonbuf::_sync() function, but I have already hacked that into a safe_gil_scoped_acquire to avoid subinterpreter-related deadlocks. Also, I'm not convinced that the GUI is actually using this pybind11 class at this point (but I could be wrong; that code is a bit old and a bit tricky - but I think what I'm doing for general stdout/stderr redirection is more at the level of the Python C API).

If anyone's looking, the relevant classes are python/gui/pythonoutputstream.{h,cpp} as well as python/gui/pythoninterpreter.{h,cpp} - this is what the GUI console actually uses for its output.

Where it actually *writes* the output to the terminal is in qtui/src/python/pythonconsole.cpp, in PythonConsole::addOutput(). If it's locking up anywhere, this is my bet as to where it is - either in the call to QTextEdit::insertHtml(), or QApplication::processEvents(). It's not inconceivable that there's something specific to windows where this is catching, since this all calls low-level platform-specific GUI code.

Anyway. Will keep trying to reproduce, but basically this is a theoretical analysis only, since I don't have any concrete deadlock happening to capture and investigate.

Nathan: when you kill the process, are you able to get any kind of useful error report? Like on macOS, when you "force quit" it asks if you want to send a report. If you say yes then it generates a report (which you don't have to send, but which includes a stack trace - which is what we really need here).

- b.

**Comment by NathanDunfield** [comment]
The only report I got was the below:
```
Source
regina-gui.exe

Summary
Stopped responding and was closed

Date
‎9/‎30/‎2022 11:28 AM

Status
Not reported

Description
A problem caused this program to stop interacting with Windows.
Faulting Application Path:	C:\Program Files\Regina\Regina 7.1\bin\regina-gui.exe

Problem signature
Problem Event Name:	AppHangB1
Application Name:	regina-gui.exe
Application Version:	0.0.0.0
Application Timestamp:	6333b779
Hang Signature:	e40f
Hang Type:	134217728
OS Version:	10.0.19044.2.0.0.256.48
Locale ID:	1033
Additional Hang Signature 1:	e40f583a3070b36dbc46e7091d560cf2
Additional Hang Signature 2:	50df
Additional Hang Signature 3:	50dfb6daae4f34ac364dfd6a99860c1c
Additional Hang Signature 4:	e40f
Additional Hang Signature 5:	e40f583a3070b36dbc46e7091d560cf2
Additional Hang Signature 6:	50df
Additional Hang Signature 7:	50dfb6daae4f34ac364dfd6a99860c1c
```

**Comment by NathanDunfield** [comment]
In general on Windows, if I double-click e.g. the SnapPea icon, then the dialog window comes up as expected but its menubar flickers between grayed out and not about 5 times before settling down in the "on" mode.  It also gets confused by the following: single-click the terminal icon and very rapidly hit the SnapPy icon.  I end up with the Python Console stuck in printing the "Regina 7.1" line and the "New SnapPea Triangulation" dialog open.  If I close the latter window, the Python Console revives and becomes usable.

**Comment by baburton** [comment]
Thanks! - with the double click I can reproduce it consistently here.

The deadlock is happening somewhere inside QApplication::processEvents(). (This is being called so that the console actually displays the output in real time even if the python command is a long-running computation.)

Anyway - now I know precisely where to look, so this is great - leave it with me. - b.

**Comment by baburton** [comment]
*Okay*. Putting here what I think is happening.

You double-click on the terminal icon. The first console fires up, and at some point - whilst holding the GIL - it runs the python welcome/banner code, which prints the welcome message to the console via PythonConsole::addOutput(). In that function there is a call to QApplication::processEvents(), which is designed to immediately write data to the graphical console while some (perhaps log-running) python code is executing.

However: that call to processEvents() now picks up the *second* click, which fires up a new terminal - all from the *same* thread that is in the middle of the python welcome code from the first. That second terminal then at some point tries to acquire the GIL (in the call to PyEval_AcquireThread() in the regina::python::PythonInterpreter constructor), and it deadlocks since the same native OS thread is trying to acquire the GIL which it already holds.

Note: the fix is _not_ a matter of just avoiding recursive GIL locks, since the second acquisition is coming from a different subinterpreter, and so the first GIL needs to be explicitly unlocked.

I wonder if the right solution is to explicitly _unlock_ the GIL in PythonConsole::addOutput() (and related functions) by saving the Python thread state, before calling QApplication::processEvents(), and then re-acquiring the Python thread state immediately afterwards. This adds overhead, but it should solve the problem that we are seeing here, and of course in theory it is possible that QApplication::processEvents() could be doing anything at all with other subinterpreters.

I might try it, and see how bad a performance hit it gives to "normal" operation. My guess is that it will be unnoticeable, since GUI output is probably much slower than Python thread state save/restore operations.

- b.

**Comment by baburton** [comment]
I've pushed a fix that hopefully fixes the issue - basically whenever it dumps output to the console, it checks whether the GIL is held and temporarily releases it if it is.

It seems to fix the double-click issue on my machine.

Nathan: there is a new Windows build at https://people.smp.uq.edu.au/BenjaminBurton/beta.html - does this fix it for you?

- Ben.

**Comment by NathanDunfield** [comment]
> Nathan: there is a new Windows build at https://people.smp.uq.edu.au/BenjaminBurton/beta.html - does this fix it for you?

Yes, it does.

**Comment by baburton** [comment]
Aieee ok, will try again to replicate and probe further.

Does it ever happen on the first python window you open? Or does it only happen after opening and closing several?

Will reopen the issue when I’m back near a real computer (but you’re welcome to do so also if you already have GitHub open).

- b.

--

Prof. Benjamin Burton
Computational Geometry & Topology Group
School of Mathematics and Physics
The University of Queensland, Australia

UQ ALLY   ::   Supporting and celebrating the diversity of sexuality, gender and sex at UQ.   Pronouns: He, him, his

On 30 Sep 2022, at 12:57 am, Nathan Dunfield ***@***.***> wrote:

﻿

Tried out with the 7.1 binary release on Windows 10 (21H2) on the same Surface Pro 5 (i5-7330 U) as in the original report. Unfortunately, the problem is still there, though it occurs much less frequently, say 1 time in 10 rather than 1 in 4.

[Untitled]<https://user-images.githubusercontent.com/3139290/193065973-8be1f1a2-b7fb-42c0-89f1-6dda6c0979d0.png>

**Comment by baburton** [comment]
Okay: reproduced with 7.1 and now fixed with 7.2, as described in the comments above. Closing this again. - Ben.
